---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/5 5:16 下午
---
local class = {}

function class.derivable(parent)
    local child = {
        __parent = parent
    }
    for i, v in pairs(parent) do
        child[i] = v
    end
    setmetatable(child, {
        __call = function(t, ...)
            local instance = {}
            setmetatable(instance, {
                __index = child
            })
            if child.__parent then
                child.__parent._construct(instance, ...)
            end
            return t._construct(instance, ...) or instance
        end
    })
    return child
end

setmetatable(class,{
    __call  = function()
        local c = {}
        setmetatable(c,{
            __call = class.derivable
        })
        return c
    end
})

return class



