---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/5 5:16 下午

local pairs, rawget, rawset, setmetatable, require = _G.pairs, _G.rawget, _G.rawset, _G.setmetatable, _G.require
local merge = require("Tilua.utils.tables").merge
local M = {}

local function getter(self, key, class)
    local v = class[key]
    if v then
        return v
    end
    v = rawget(class, 'get_' .. key)
    if v then
        return v(self)
    end
end

local function setter(t, key, value, class)
    local p = 'set_' .. key
    local set = class[p]
    if set then
        set(t, value)
    else
        rawset(t, key, value)
    end
end

local function get_definable_class()
    local class = {}
    class.define = function
    ()
        return M.define(class)
    end

    return class
end
function M.is_sub_class(parent,child)
    if not parent or not child then
        return false
    end
    if not child.__parent then
        return false
    end
    return parent == child.__parent
end

function M.define(parent)
    local child = get_definable_class()
    if parent then
        child = merge(child, parent)
    end
    child.__parent = parent
    setmetatable(child, {
        __call = function(t, ...)
            local instance = {}
            setmetatable(instance, {
                __index = function(self, name)
                    return getter(self, name, child)
                end,
                __newindex = function(self, name, value)
                    return setter(self, name, value, child)
                end
            })
            if child.__parent then
                child.__parent._construct(instance, ...)
            end
            return t._construct(instance, ...) or instance
        end
    })
    return child
end

setmetatable(M, {
    __call = function()
        local c = get_definable_class()
        setmetatable(c, {
            __call = M.define
        })
        return c
    end
})

return M



