---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/7/30 2:45 下午
---
---
local m_balancers = {}
local m_services = {}
local m_upstreams = {}
local m_upstreams_services = {}
local m_services_upstreams = {}
local m_targets = {}
local m_targets_upstreams = {}
local m_upstreams_targets = {}

local dns = require("resty.dns.client")
local util = require("Tilua.util")
local crc32 = ngx.crc32_short
local routes = require("ApiGateWay.routes")
local certificate = require("ApiGateWay.certificate")

local balancer_types = {
    ["consistent-hashing"] = require("resty.dns.balancer.ring"),
    ["least-connections"] = require("resty.dns.balancer.least_connections"),
    ["round-robin"] = require("resty.dns.balancer.ring")
}

local balancer = {}

function balancer.init()
    dns.init()
end

function balancer.ev_handler(data, event, source, pid)
    ngx.log(ngx.ERR, source, '-', event, '-', util.json_encode(data), '-', pid)
    if source == 'upstream' then
        if event == 'update' then
        elseif event == 'add' then
        elseif event == 'delete' then
        end
    elseif source == 'target' then
        if event == 'update' then
            ngx.log(ngx.ERR, source, '-', event, '-', util.json_encode(m_targets), '-', pid)

            local pre_target = m_targets['t' .. data.id]
            if pre_target.host == data.host and pre_target.port == data.port and pre_target.weight == data.weight then
                return
            end
            if m_balancers["t" .. data.upstreamid] then
                m_balancers["t" .. data.upstreamid]:removeHost(pre_target.host, tonumber(pre_target.port))
                m_balancers["t" .. data.upstreamid]:addHost(data.host, tonumber(data.port), tonumber(data.weight))
            end
            balancer.remove_upstream_target(data.upstreamid, data.id)
            table.insert(m_upstreams_targets["t" .. data.upstreamid], data)
            m_targets['t' .. data.id] = data
        elseif event == 'add' then
            table.insert(m_upstreams_targets["t" .. data.upstreamid], data)
            m_targets['t' .. data.id] = data
            if m_balancers["t" .. data.upstreamid] then
                m_balancers["t" .. data.upstreamid]:addHost(data.host, tonumber(data.port), tonumber(data.weight))
            end
            m_targets_upstreams["t" .. data.id] = m_upstreams["t" .. data.upstreamid]
        elseif event == 'delete' then
            local pre_target = m_targets['t' .. data]
            local upstream = m_targets_upstreams["t" .. data]
            if m_balancers["t" .. upstream.id] then
                m_balancers["t" .. upstream.id]:removeHost(pre_target.host, tonumber(pre_target.port))
            end
            balancer.remove_upstream_target(upstream.id, data)
            m_targets['t' .. data] = nil
        end
    elseif source == 'service' then
        if event == 'update' then
            m_services['t' .. data.id] = data
        elseif event == 'add' then
            m_services['t' .. data.id] = data
        elseif event == 'delete' then
            m_services['t' .. data.id] = nil
            m_services_upstreams['t' .. data.id] = nil
        end
    elseif source == 'route' then
        routes.reload_routes()
    elseif source == 'certificate' then
        certificate.reload()
    end
end

function balancer.remove_upstream_target(upstreamid, tagetid)
    local index = -1
    for i, v in ipairs(m_upstreams_targets["t" .. upstreamid]) do
        if v.id == tagetid then
            index = i
        end
    end
    if index > 0 then
        table.remove(m_upstreams_targets["t" .. upstreamid], index)
    end
    return index
end

function balancer.get_service(serviceid, ctx)
    ctx = ctx or ngx.ctx.ctx
    if not m_services["t" .. serviceid] then
        m_services["t" .. serviceid] = ctx.model.services:find(serviceid)
    end
    return m_services["t" .. serviceid]
end

function balancer.get_upstream(service, ctx)
    ctx = ctx or ngx.ctx.ctx
    local upstream = m_services_upstreams["t" .. service.id]
    if not upstream then
        upstream = ctx.model.upstreams:where({
            name = service.host
        })            :find()
        if not upstream then
            return nil
        end
        m_services_upstreams["t" .. service.id] = upstream
        m_upstreams_services["t" .. upstream.id] = service
        m_upstreams["t" .. upstream.id] = upstream
    end
    return upstream
end

function balancer.get_targets(upstream, ctx)
    ctx = ctx or ngx.ctx.ctx
    if not m_upstreams_targets["t" .. upstream.id] then
        m_upstreams_targets["t" .. upstream.id] = ctx.model.targets:where({
            upstreamid = upstream.id
        })                                           :select()
        for _, v in ipairs(m_upstreams_targets["t" .. upstream.id]) do
            m_targets_upstreams["t" .. v.id] = upstream
            m_targets['t' .. v.id] = v
        end
    end
    return m_upstreams_targets["t" .. upstream.id]
end

function balancer.add_targets(bal, targets, start)
    for i = start, #targets do
        local target = targets[i]
        if target.weight > 0 then
            assert(bal:addHost(target.host, target.port, target.weight))
        else
            assert(bal:removeHost(target.host, target.port))
        end
    end
end

function balancer.create_balancer(upstream, ctx, force_create)
    local health_threshold = upstream.healthchecks and
            upstream.healthchecks.threshold or nil

    if m_balancers["t" .. upstream.id] and not force_create then
        return m_balancers["t" .. upstream.id]
    end

    local bal, err = balancer_types[upstream.algorithm].new({
        log_prefix = "upstream:" .. upstream.name,
        wheelSize = upstream.slots, -- will be ignored by least-connections
        dns = dns,
        healthThreshold = health_threshold,
    })
    if not bal then
        return nil, "failed creating balancer:" .. err
    end

    local targets = balancer.get_targets(upstream, ctx)
    if targets then
        balancer.add_targets(bal, targets, 1)
    end
    m_balancers["t" .. upstream.id] = bal
    return bal
end

function balancer.create_hash(upstream, ctx)
    if not upstream then
        return nil
    end

    local request = ctx.request
    local hash_on = upstream.hash_on
    if hash_on == "none" or hash_on == nil or hash_on == ngx.null then
        return
    end
    local identifier
    local header_field_name = "hash_on_header"
    for _ = 1, 2 do

        if hash_on == "consumer" then

        elseif hash_on == "ip" then
            identifier = request.remote_addr
        elseif hash_on == "header" then
            identifier = request.header[upstream[header_field_name]]
            if type(identifier) == "table" then
                identifier = table.concat(identifier)
            end
        elseif hash_on == "cookie" then
            identifier = request.cookie[upstream.hash_on_cookie]
            if not identifier then
                identifier = util.uuid()
                ctx.response:set_cookie(upstream.hash_on_cookie, identifier, upstream.hash_on_cookie_path or '/')
            end
        end

        if identifier then
            return crc32(identifier)
        end

        -- we missed the first, so now try the fallback
        hash_on = upstream.hash_fallback
        header_field_name = "hash_fallback_header"
        if hash_on == "none" then
            return nil
        end
    end
end

return balancer