---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/4 9:09 上午
---certificate.lua
---
local ngx_ssl = require "ngx.ssl"
local parse_pem_cert = ngx_ssl.parse_pem_cert
local parse_pem_priv_key = ngx_ssl.parse_pem_priv_key
local pl_utils = require("pl.utils")

local certificate = {}
local pem_certs = {}
local default_cert_and_key = {}
local cert_loaded = false
local M = {}

function M.find_key_and_cert(server_name)
    if pem_certs[server_name] then
        return pem_certs[server_name]
    end
    local matched_cert = certificate[server_name] or default_cert_and_key
    local cert, err = parse_pem_cert(matched_cert.cert)
    if not cert then
        return nil, "could not parse PEM certificate: " .. err
    end
    local key, err = parse_pem_priv_key(matched_cert.key)
    if not key then
        return nil, "could not parse PEM private key: " .. err
    end
    pem_certs[server_name ] = {
        cert = cert,
        key = key
    }
    return pem_certs[server_name ]
end

function M.reload()
    cert_loaded = false
end

function M.load_default_cert_and_key(cert,key)
    default_cert_and_key = {
        cert = cert,
        key = key
    }
end

function M.load_cert_and_key(ctx)
    if cert_loaded then
        return
    end
    ctx.logger:debug("start to load_cert_and_keys --- ")
    default_cert_and_key = {
        cert = pl_utils.readfile(ctx.config.default_ssl_cert),
        key = pl_utils.readfile(ctx.config.default_ssl_key)
    }
    local cert = ctx.model.certificate:where({
        status = 1
    }):select()
    for _, v in ipairs(cert) do
        certificate[v.server_name] = {
            cert = v.cert,
            key = v.cert_key
        }
    end
    cert_loaded = true
end


return M