---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/2 9:22 下午
---

local M = {}
local lw_util = require("Tilua.util")

function M.get_route_midwares(ctx, phase, routeid)
    local db = ctx.db.instance()
    local sql = [[select mid.package,mid.config as midconfig,route.config from plugins as route left join midwares as mid
    on (mid.id=route.mid) where route.objecttype="route" and  route.objectid = ]]
    local data = db:query(sql .. routeid .. " and route.phase = '" .. phase .. "'")
    local midwares = {}
    for _, mid in ipairs(data) do
        table.insert(midwares, {
            mid.package,
            lw_util.parse_expression(mid.config == ngx.null and "" or mid.config, ',', '=')
        })
    end
    return midwares
end

function M.get_secret_midwares(ctx, phase, secretid)
    local db = ctx.db.instance()
    local sql = [[select mid.package,mid.config as midconfig,route.config from plugins as route left join midwares as mid on (mid.id=route.mid)
    where route.objecttype="secret" and  route.objectid = ]]
    local data = db:query(sql .. secretid .. " and route.phase = '" .. phase .. "'")
    local midwares = {}
    for _, mid in ipairs(data) do
        table.insert(midwares, {
            mid.package,
            lw_util.parse_expression(mid.config == ngx.null and "" or mid.config, ',', '=')
        })
    end
    return midwares
end

function M.get_service_midwares(ctx, phase, serviceid)
    local db = ctx.db.instance()
    local sql = [[select mid.package,mid.config as midconfig,route.config from plugins as route left join midwares as mid on (mid.id=route.mid)
    where route.objecttype="service" and  route.objectid = ]]
    local data = db:query(sql .. serviceid .. " and route.phase = '" .. phase .. "'")
    local midwares = {}
    for _, mid in ipairs(data) do
        table.insert(midwares, {
            mid.package,
            lw_util.parse_expression(mid.config == ngx.null and "" or mid.config, ',', '=')
        })
    end
    return midwares
end

return M