---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/5/29 4:36 下午
---
---
---
local util = require("Tilua.utils.util")
local json_encode = util.json_encode
local json_decode = util.json_decode

local proxy_dispatch = require("Tilua.dispatch").derive()
local trim = require("pl.stringx").strip
local dns = require("resty.dns.client")
local balancer = require("ApiGateWay.balancer")

function proxy_dispatch:_init(ctx)
    self:super(ctx)
end

function proxy_dispatch:get_striped_path(router)
    local matched_route = router.router.route
    local striped_path
    if matched_route.strip_path == 1 then
        striped_path = table.concat(router.params, '/')
        if matched_route.path_handle ~= 'v1' then
            striped_path = "/" .. striped_path
        end
    else
        striped_path = trim(ngx.var.uri, '/')
        if matched_route.path_handle ~= 'v1' then
            striped_path = "/" .. striped_path
        end
    end
    if ngx.var.is_args == "?" or string.sub(ngx.var.request_uri, -1) == "?" then
        striped_path = striped_path .. "?" .. (ngx.var.args or "")
    end
    return striped_path
end

function proxy_dispatch:run(router)
    if not router.proxy then
        ngx.exit(404)
        return
    end
    local ctx = self.ctx
    local model = ctx.model
    local handler = {}
    if router.proxy.type == 'baffle' then
        handler = function()
            local baffle = model.baffle:find(router.proxy.serviceid)
            local response = ctx.response
            local header = json_decode(baffle.header)
            util.foreach(header, function(v)
                response:add_header(v)
            end)
            response.body = baffle.body
        end
    else
        local service = balancer.get_service(router.proxy.serviceid, self.ctx)
        if not service then
            ngx.exit(404)
            return
        end
        local matched_route = router.router.route
        local upstream_base = '/' .. trim(service.path, '/')
        handler = function()
            local upstream = balancer.get_upstream(service, ctx)
            ngx.var.upstream_scheme = service.protocol
            if matched_route.protocols == 'HTTP' then
                ngx.var.upstream_uri = upstream_base .. self:get_striped_path(router)
                self.ctx.logger:debug("upstream uri ", ngx.var.upstream_uri)
            end
            ngx.var.upstream_connection = ctx.request.header.connection or ''
            if matched_route.preserve_host == 1 then
                ngx.var.upstream_host = ctx.request.host .. ":" .. ctx.request.server_port
            elseif upstream then
                ngx.var.upstream_host = upstream.host_header ~= "" and upstream.host_header or "TiluaApiGateway"
            else
                ngx.var.upstream_host = "TiluaApiGateway"
            end
            self.ctx.logger:debug("upstream host -> ", ngx.var.upstream_host)
            local ip, port, host, handle, hash_value
            if ngx.ctx.peer then
                handle = ngx.ctx.peer.handle
            end

            hash_value = ngx.ctx.peer and ngx.ctx.peer.hash_value or balancer.create_hash(upstream, ctx)
            if upstream then
                local bal,err = balancer.create_balancer(upstream, ctx, false)
                if not bal then
                    self.ctx.logger:debug("upstream backend ",err )
                    return 500
                end
                ip, port, host, handle = bal:getPeer(true,
                        handle,
                        hash_value
                )
            else

                ip = dns.toip(service.host)
                port = service.port
            end
            return {
                host = ip,
                port = port,
                connect_timeout = service.connect_timeout,
                send_timeout = service.write_timeout,
                read_timeout = service.read_timeout,
                handle = handle,
                hash_value = hash_value
            }
        end
    end
    handler = self:create_responser({
        handler,{},router.midware
    })
    local response = self:prepare_response(handler())
    if router.proxy.type == 'baffle' then
        response:send()
    else
        if response.status ~= 0 and response.status ~= 200 then
            response:send()
        else
            ngx.ctx.peer = response.body
        end
    end
end

return proxy_dispatch