---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/6/12 4:39 下午
---
local lw_util = require("Tilua.util")
local is_routes_loaded = false
local routes = {}
local lw_utils = require("Tilua.util")
local split = require("pl.utils").split
local add_route_rule = require("Tilua.route").add_route_rule
local parse_validation = require("Tilua.route").parse_validation
local clear_route_rule = require("Tilua.route").clear_route_rule
local midwares = require("ApiGateWay.plugins")

function routes.get_midwares(ctx, id)
    local db = ctx.db.instance()
    local data = db:query("select mid.package,mid.config as midconfig,route.config from routes_plugins as route left join midwares as mid on (mid.id=route.mid) where route.routeid=" .. id)
    local midwares = {}
    for _, mid in ipairs(data) do
        table.insert(midwares, {
            mid.package,
            lw_util.parse_expression(mid.config == ngx.null and "" or mid.config, ',', '=')
        })
    end
    return midwares
end

function routes.get_midwares()

end

function routes.reload(ctx)
    routes.load(ctx, true)
end

function routes.reload_routes()
    is_routes_loaded = false
end
function routes.parse_validation(route)
    local validations = {}
    if route.hosts ~= '' then
        validations['request.host'] = {
            'IN',
            split(route.hosts, ',')
        }
    end
    if route.headers ~= '' then
        local headers = lw_utils.parse_expression(route.headers)
        for k, v in pairs(headers) do
            validations['request.header.' .. k] = {
                'EQ',
                v
            }
        end
    end
    if route.validations ~= '' then
        local va = parse_validation(route.validations)
        for k, v in pairs(va) do
            validations[k] = v
        end
    end

    return validations
end

function routes.load(ctx, force)
    if not is_routes_loaded or force then
        is_routes_loaded = true
        clear_route_rule(ctx.name)
        ctx.logger:debug("start load routes")
        local _routes = ctx.model.routes:select()
        lw_utils.foreach(_routes, function(route)
            local methods = split(route.methods, ',', true)
            local paths = split(route.paths, ',', true)
            local validations = routes.parse_validation(route)
            lw_utils.foreach(methods, function(verb)
                lw_utils.foreach(paths, function(path)
                    add_route_rule(
                            ctx.name,
                            string.lower(verb),
                            '*',
                            path,
                            {
                                {
                                    responser = {
                                        type = route.proxy_type,
                                        serviceid = route.serviceid
                                    },
                                    midware = midwares.get_route_midwares(ctx, 'content', route.id),
                                    path = path,
                                    route = route
                                },
                                validations
                            }
                    )
                end)
            end)
        end)

    end
end

return routes