---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/12 2:46 下午
---
local route = require("Tilua.route")

route.group(function()
    route.rest('^/(services|certificate|secrets|targets|routes|upstreams|baffle|midwares)', 'controller.$1')

    route['=/certificate_sync'] = 'controller.certificate@sync'
    route['/'] = '/'

end, 'json', 'body_parser')