---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/6/12 4:39 下午
---
local lw_util = require("Tilua.util")

local routes = {}

function routes.get_midwares(ctx, id)
    local db = ctx.db.instance()
    local data = db:query("select mid.package,mid.config as midconfig,route.config from routes_plugins as route left join midwares as mid on (mid.id=route.mid) where route.routeid=" .. id)

    local midwares = {}

    for _, mid in ipairs(data) do
        table.insert(midwares, {
            mid.package,
            lw_util.parse_expression(mid.config == ngx.null and "" or mid.config, ',', '=')
        })
    end

    return midwares
end

return routes