---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/7/12 10:06 上午
---
local http = require "resty.http"
local lw_util = require("Tilua.utils.util")
local reduce = require("pl.tablex").reduce
local bind1 = lw_util.bind1
local json_encode = lw_util .json_encode
local json_decode = lw_util .json_decode
local util = {}
function util.apiv1(request, method, headers, time_out)
    return util.request("http://32.254.48.88/api/v1", request, method, headers, time_out)
end

function util.apiv2(request, method, headers, time_out)
    return util.request("http://32.254.48.88/api/v2", request, method, headers, time_out)
end

function util.do_chain_call(ctx, midware, handler, ...)
    return reduce(function(res, next_midware)
        local mid = ctx.midware.instance(next_midware)
        local func = bind1(mid.handle, mid)
        return function(...)
            return func(res, ...)
        end
    end, lw_util.reverseTable(midware or {}), handler)(...)
end

function util.call_midwares_stack(ctx, midwares, ...)
    local phase = ctx.phase
    for _, midware in ipairs(midwares) do
        local mid = ctx.midware.instance(midware)
        local func = mid["handle_"..phase]
        if func then
            func(mid,...)
        end
    end
end

function util.request(api, request, method, headers, time_out)
    local httpc = http.new()

    method = method or "POST"
    headers = headers or {}

    time_out = time_out and time_out * 1000 or 5000

    local trequest = type(request)
    if trequest == 'string' then
        if not headers['Content-Type'] then
            headers['Content-Type'] = 'application/x-www-form-urlencode'
        end
    elseif trequest == 'table' then
        request = json_encode(request) or request
        headers["Content-Type"] = "application/json;chartset=uft-8"
    end

    httpc:set_timeout(time_out)

    local res, err = httpc:request_uri(api, {
        method = method,
        body = request,
        headers = headers,
        keepalive_timeout = 30000,
        keepalive_pool = 10
    })
    if res.status ~= 200 then
        return nil
    end
    if not err then
        if res.headers['Content-Type'] == 'application/json; charset=utf-8' then
            res.body = json_decode(res.body) or res.body
        end
        if res.body.code == 0 then
            return res.body.data
        end
        return nil, res.body.desc
    end
    return nil
end

return util