---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/5/26 9:06 上午
---
local pl_file = require("pl.file")
local pl_date = require("pl.Date")
local path = require("pl.path")
local lw_utils = require('Tilua.util')

local file = {}
local log_path = ""
local log_file = ""
function file.init(config)
    ngx.update_time()
    log_path = config.path
    if not path.isdir(log_path) then
        local ok, err = path.mkdir(log_path)
        assert(ok, 'failed to create log path ' .. log_path)
    end
    log_file = log_path .. '/' .. pl_date.Format("yyyy_mm_dd"):tostring(os.time()) .. '.log'
end

function file.flush(logs)
    local _file = io.open(log_file, "a+")
    io.output(_file)
    for i, v in ipairs(logs) do
        if v.level == "" then
            io.write(v.msg .. "\n")
        else
            io.write("[" .. v.level .. "]: " .. v.msg .. "\n")
        end
    end
    io.close(_file)
end

return file