---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/7/12 10:06 上午
---
local http = require "resty.http"
local json_encode = require "Tilua.util" .json_encode
local json_decode = require "Tilua.util" .json_decode

local util = {}

function util.api_v2(request, method, headers, time_out)
    local httpc = http.new()

    method = method or "POST"
    headers = headers or {}

    time_out = time_out and time_out * 1000 or 5000

    local trequest = type(request)
    if trequest == 'string' then
        if not headers['Content-Type'] then
            headers['Content-Type'] = 'application/x-www-form-urlencode'
        end
    elseif trequest == 'table' then
        request = json_encode(request) or request
        headers["Content-Type"] = "application/json;chartset=uft-8"
    end

    httpc:set_timeout(time_out)

    local res, err = httpc:request_uri("http://32.254.48.88/api/v2", {
        method = method,
        body = request,
        headers = headers,
        keepalive_timeout = 30000,
        keepalive_pool = 10
    })
    if res.status ~= 200 then
        return nil
    end
    if not err then
        if res.headers['Content-Type'] == 'application/json; charset=utf-8' then
            res.body = json_decode(res.body) or res.body
        end
        if res.body.code == 0 then
            return res.body.data
        end
        return nil, res.body.desc
    end
    return nil
end

return util