---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/4 3:58 下午
---

local route = require("Tilua.route")

local function getnavs(module, action)
    return {
        {
            title = "Lua 基础",
            items = {
                {
                    title = "简介",
                    href = "/lua/introduce.html",
                    em = "Lua Introduce",
                    this = module == 'lua' and action == 'introduce'
                },
                {
                    title = "环境搭建",
                    href = "/lua/build_env.html",
                    em = "Lua build env",
                    this = module == 'lua' and action == 'build_env'
                },
                {
                    title = "编辑器选择",
                    href = "/lua/editor.html",
                    em = "Lua editor",
                    this = module == 'lua' and action == 'editor'
                },
                {
                    title = "数据类型",
                    href = "/lua/class.html",
                    em = "Lua types",
                    this = module == 'lua' and action == 'class'
                }
            }
        }
    }
end
route['/'] = function
(ctx)
    return "index.html", {
        navs = getnavs('lua', 'introduce'),
        nav = 'lua-introduce',
        module = 'lua',
        action = 'introduce'
    }
end

route['~^/{module}/{action}1212ahtml$'] = function
(ctx, module, action)
    return "index.html", {
        navs = getnavs(module, action),
        nav = module .. '-' .. action,
        module = module,
        action = action
    }
end