---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/4 3:58 下午
---

local route = require("Tilua.route")

local function getnavs(module, action)
    return {
        {
            title = "Lua 基础",
            items = {
                {
                    title = "简介",
                    href = "/lua/introduce.html",
                    em = "Lua Introduce",
                    this = module == 'lua' and action == 'introduce'
                },
                {
                    title = "基本语法",
                    href = "/lua/syntax.html",
                    em = "Basic syntax",
                    this = module == 'lua' and action == 'syntax'
                },
                {
                    title = "数据类型",
                    href = "/lua/types.html",
                    em = "types",
                    this = module == 'lua' and (
                            action == 'types' or
                            action =='strings' or
                            action == 'arrays' or
                            action == 'tables' or
                            action == 'functions'
                    )
                },
                {
                    title = "变量",
                    href = "/lua/variables.html",
                    em = "variables",
                    this = module == 'lua' and action == 'variables'
                },
                {
                    title = "运算符",
                    href = "/lua/operator.html",
                    em = "operator",
                    this = module == 'lua' and action == 'operator'
                },
                {
                    title = "迭代器",
                    href = "/lua/iterators.html",
                    em = "iterators",
                    this = module == 'lua' and action == 'iterators'
                },
                {
                    title = "模块与包",
                    href = "/lua/packages.html",
                    em = "package",
                    this = module == 'lua' and action == 'packages'
                },
                {
                    title = "元表(Metatable)",
                    href = "/lua/metatables.html",
                    em = "metatable",
                    this = module == 'lua' and action == 'metatables'
                },
                {
                    title = "协同程序(coroutine)",
                    href = "/lua/coroutine.html",
                    em = "coroutine",
                    this = module == 'lua' and action == 'coroutine'
                },
                {
                    title = "文件 I/O",
                    href = "/lua/fileio.html",
                    em = "fileio",
                    this = module == 'lua' and action == 'fileio'
                },
                {
                    title = "错误处理",
                    href = "/lua/error-handling.html",
                    em = "error handle",
                    this = module == 'lua' and action == 'error-handling'
                },
                {
                    title = "面向对象",
                    href = "/lua/object-oriented.html",
                    em = "object oriented",
                    this = module == 'lua' and action == 'object-oriented'
                },
                {
                    title = "数据库访问",
                    href = "/lua/database-access.html",
                    em = "database access",
                    this = module == 'lua' and action == 'database-access'
                }
            }
        },
        {
            title = "Nginx 起步",
            items = {

            }
        },
        {
            title = "Tilua 基础",
            items = {

            }
        },
        {
            title = "Tilua 配置",
            items = {

            }
        },
        {
            title = "Tilua 路由",
            items = {

            }
        },
        {
            title = "Tilua 控制器",
            items = {

            }
        },
        {
            title = "Tilua 模型",
            items = {

            }
        },
        {
            title = "Tilua 视图",
            items = {

            }
        },
        {
            title = "Tilua 模板",
            items = {

            }
        }
    }
end
route['/'] = function
(ctx)
    return "index.html", {
        navs = getnavs('lua', 'introduce'),
        nav = 'lua-introduce',
        module = 'lua',
        action = 'introduce'
    }
end
route['=/test'] = function
(ctx)
    --ngx.re.gmatch
    ctx.response.body = 1
end
route['~^/{module}/{action}.html$'] = function
(ctx, module, action)
    return "index.html", {
        navs = getnavs(module, action),
        nav = module .. '-' .. action,
        module = module,
        action = action
    }
end