---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/6/23 5:45 下午
---

local session_check = require('Tilua.midware.base').define()

function session_check:handle(next, ...)
    local request, response = self.ctx:unpack()
    if self.ctx.session:get('user') then
        return next(...)
    end
    response.redirect('/user/login')
end

return session_check