lua_package_path '$prefix/../lua/?.lua;$prefix/../lualib/?.lua;$prefix/../lualib/Tilua/support/?.lua;';
lua_package_cpath '$prefix/../lualib/?.so;/usr/local/lib/lua/5.1/?.so;$prefix/../lualib/Tilua/support/?.so;';

lua_shared_dict events 10m;
lua_shared_dict service_cache 10m;
lua_shared_dict route_cache 10m;

lua_code_cache on;

server {
        listen 8002;
        location ~/.*\.(ttf|rar|css|js|jpg|jpeg|png|gif|ico|woff|woff2|eot|svg|css\.map|min\.map|docx|xlsx|cab|apk).*$ {
                root /usr/local/openresty/lua/Lwhc/;
                add_header Access-Control-Allow-Origin *;
                keepalive_timeout  0;
                expires 7d;
        }
        location / {
                content_by_lua_block {
                    LwhcApp = require 'Lwhc.app'
                    LwhcApp:content_by_lua()
                }
                log_by_lua_block           {
                    LwhcApp:log_by_lua()
                }
        }
}