---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/5 8:21 下午
---

local class = require("Tilua.utils.class")

local M = class.define()

function M:_construct(config, ctx, logger)
    self.ctx = ctx
    self.config = config
    self.logger = logger
end

return M