---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/5/30 6:34 下午
---
local lw_util = require('Tilua.util')

local manager = {}

function manager.instance()

end

---get
---@param key string
function manager.get(key)
    return cache.instance(context.config.data_cache_type):get(context.config.data_cache_prefix .. key)
end
---set
---@param name string
---@param value any
---@param expire number
function manager.set(name, value, expire)
    return cache.instance(context.config.data_cache_type):set(context.config.data_cache_prefix .. name, value, expire)
end

---del
---@param name string
function manager.del(name)
    return cache.instance(context.config.data_cache_type):del(context.config.data_cache_prefix .. name)
end

function manager.new(ctx)
    local manager_inst = {
        ctx = ctx,
        instances = {}
    }
    return setmetatable(manager_inst, {
        __index = function(this, name)
            if type(name) == 'string' then
                name = { type = name }
            end
            local hash = lw_util.get_hash(name)
            if this.instances[hash] then
                return this.instances[hash]
            end
            local ok, driver = pcall(require, "Tilua.cache.driver." .. name.type)
            assert(ok, 'unsupported cache type ' .. name.type)
            this.instances[hash] = driver(name, self)
            return this.instances[hash]
        end,
        __call = function()

        end
    })
end

return manager