---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/6 9:34 上午
---
local get_timestamp = require("Tilua.utils.util").get_now_ms
local base = require("Tilua.cache.base")
local M = base.define()
local store = {}
---construct
---@param config table
---@param ctx app
function M:_construct(config, ctx)
    self.namespace = config.namespace or ctx.name
    store[self.namespace] = store[self.namespace] or {}
end

---@param key string
---@return boolean
function M:exists(key)
    return self:get(key) == nil
end

---del
---@param key string
---@return boolean
function M:del(key)
    store[self.namespace][key] = nil
    return true
end

---expire
---@param key string
---@param exptime number
function M:expire(key, exptime)
    if self:exists(key) then
        store[self.namespace][key].expires = get_timestamp() + exptime
        return true
    end
    return false
end

---get
---@param key string
---@return any
function M:get(key)
    local value = store[self.namespace][key]
    if value then
        if value.expires == -1 or get_timestamp() > value.expires() then
            return value.data
        end
    end
    return nil
end

---set
---@param key string
---@param value any
---@param expires number
function M:set(key, value, expires)
    store[self.namespace][key] = {
        data = value,
        expires = expires and (get_timestamp() + expires) or -1
    }
    return true
end

return M