---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/2 9:22 下午
---

local M = {}
local lw_util = require("Tilua.utils.util")
local is_plugins_loaded = false
local plugins = {}
function M.load(ctx)
    if is_plugins_loaded then
        return
    end
    plugins[ctx.name] = {}
    local db = ctx.db.instance()
    local sql = [[select mid.package,plugins.config,plugins.phase,plugins.objecttype,plugins.objectid from plugins  left join midwares as mid
    on (mid.id=plugins.mid) where plugins.status =1 order by plugins.indexNo asc ]]
    local data = db:query(sql)
    if not data then
        return false
    end
    for _, mid in ipairs(data) do
        plugins[ctx.name][mid.objecttype] = plugins[ctx.name][mid.objecttype] or {}
        plugins[ctx.name][mid.objecttype][mid.phase] = plugins[ctx.name][mid.objecttype][mid.phase] or {}
        plugins[ctx.name][mid.objecttype][mid.phase]['t' .. mid.objectid] = plugins[ctx.name][mid.objecttype][mid.phase]['t' .. mid.objectid] or {}
        table.insert(plugins[ctx.name][mid.objecttype][mid.phase]['t' .. mid.objectid], {
            mid.package,
            lw_util.parse_expression(mid.config == ngx.null and "" or mid.config, ',', '=')
        })
    end
    is_plugins_loaded = true
end

function M.get_midwares(ctx,objecttype,objectid,phase)
    if plugins[ctx.name][objecttype] and plugins[ctx.name][objecttype][phase] and plugins[ctx.name][objecttype][phase]['t'..objectid] then
        return plugins[ctx.name][objecttype][phase]['t'..objectid]
    end
    return {}
end

return M