---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/6/12 4:39 下午
---
local lw_util = require("Tilua.utils.util")
local is_routes_loaded = false
local routes = {}
local lw_utils = require("Tilua.utils.util")
local tablex = require("pl.tablex")
local split = require("pl.utils").split
local add_route_rule = require("Tilua.route").add_route_rule
local parse_path_to_regex = require("Tilua.route").parse_path_to_regex
local parse_validation = require("Tilua.route").parse_validation
local clear_route_rule = require("Tilua.route").clear_route_rule
local midwares = require("ApiGateWay.service.plugins")
local prefix_midwares = {}

local re_match = ngx.re.match

function routes.find_prefix_midwares(ctx)
    routes.load(ctx,false)

    local pathinfo = ctx.request.path_info
    local method = string.lower(ctx.request.method)
    local mids = {}
    ctx.logger:debug("find_prefix_midwares prefix:", pathinfo, ' method:', method, lw_utils.json_encode(prefix_midwares[ctx.name]))
    for _, v in ipairs(prefix_midwares[ctx.name]) do
        if tablex.find(v.method, '*') or tablex.find(v.method, method) then
            if v.matcher == '=' and v.path == pathinfo then
                ctx.logger:debug("find_prefix_midwares prefix path:", v.path, " pathinfo:", pathinfo)
                tablex.move(mids, v.midwares)
            elseif v.matcher == '~' and re_match(pathinfo, v.path, 'jo') then
                tablex.move(mids, v.midwares)
            elseif v.matcher == '*' and string.find(pathinfo, v.path, 1, true) then
                tablex.move(mids, v.midwares)
            end
        end
    end
    ctx.logger:debug("find_prefix_midwares prefix:", pathinfo, ' method:', method, ' midwares:', lw_utils.json_encode(mids))
    return mids
end

function routes.reload(ctx)
    routes.load(ctx, true)
end

function routes.reload_routes()
    is_routes_loaded = false
end
function routes.parse_validation(route)
    local validations = {}
    if route.hosts ~= '' then
        validations['request.host'] = {
            'IN',
            split(route.hosts, ',')
        }
    end
    if route.headers ~= '' then
        local headers = lw_utils.parse_expression(route.headers)
        for k, v in pairs(headers) do
            validations['request.header.' .. k] = {
                'EQ',
                v
            }
        end
    end
    if route.validations ~= '' then
        local va = parse_validation(route.validations)
        for k, v in pairs(va) do
            validations[k] = v
        end
    end

    return validations
end

function routes.load(ctx, force)
    if not is_routes_loaded or force then
        is_routes_loaded = true
        clear_route_rule(ctx.name)
        ctx.logger:debug("start load routes")
        local _routes, err = ctx.model.routes:select()
        if err then
            error(err)
        end
        prefix_midwares[ctx.name] = {}

        lw_utils.foreach(_routes, function(route)
            local methods = split(string.lower(route.methods), ',', true)
            local paths = split(route.paths, ',', true)
            local validations = routes.parse_validation(route)

            lw_utils.foreach(paths, function(path)
                local pre_mid = midwares.get_midwares(ctx, 'route', route.id, 'access')
                if pre_mid then
                    table.insert(prefix_midwares[ctx.name], {
                        matcher = route.matcher,
                        path = path,
                        method = methods,
                        midwares = pre_mid,
                        phase = 'access'
                    })
                end
                local _, regex, args
                if route.matcher == '~' then
                     _, regex, args =parse_path_to_regex(path)
                end


                add_route_rule(ctx.name,{
                    matcher = route.matcher,
                    method = methods,
                    path = path,
                    regex = regex,
                    args = args,
                    responser = {
                        type = route.proxy_type,
                        serviceid = route.serviceid
                    },
                    midware = midwares.get_midwares(ctx, 'route', route.id, 'content'),
                    path = path,
                    route = route,
                    api = true,
                    validation = validations
                })
            end)
        end)
    end
end

return routes