---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/6/28 5:06 下午
---

local M =  {}

function M.list(_,range)
    return "record_list.html", {
        history = range == 'current' and 0 or 1
    }
end

function M.index(ctx,tab)
    local request, _ = ctx:unpack()
    local req = request.body
    local page = req.page or 1
    local limit = req.limit or 10

    local user = ctx.session:get('user')
    local where = {
        jgma = user.jgma
    }
    if req.certNo and req.certNo ~= '' then
        where.certNo = req.certNo
    end
    if req.certName and req.certName ~= '' then
        where.certName = {
            'like',
            '%' .. req.certName .. '%'
        }
    end
    if req.start and req.start ~= '' then
        where.rtime = {
            'gt',
            req.start
        }
    end
    if req['end'] and req['end'] ~= '' then
        where.rtime = {
            'lt',
            req['end']
        }
    end
    return {
        code = 0,
        count = ctx.model[tab]:where(where):count(),
        data = ctx.model[tab]:where(where):field('check', true):order('recordid desc'):limit((page - 1) * limit, limit):select()
    }
end

function M.view(ctx,certNo, id)
    local record = ctx.model.record
    local picp_cert = ctx.model.picp_cert:where({
        certno = certNo
    })                   :find()
    local record_data = record:where({
        recordid = id
    })                        :find()
    if not record_data then
        return ctx.response:jump('/', false, '记录不存在，请确认!')
    end
    record_data.fileid = picp_cert.fileid
    local result = {
        ['00'] = "[00] 号码与姓名一致且照片存在",
        ['01'] = "[01] 号码与姓名一致且照片不存在",
        ['02'] = "[02] 号码存在但与姓名不一致",
        ['03'] = "[03] 号码不存在",
        ['04'] = "网络繁忙，查询失败，稍后再试...",
        ['06'] = "外网系统已关闭，请于其他时间进行查询！"
    }
    record_data.resultmsg = result[record_data.result]
    return 'record.html', record_data
end

return M