---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/6/28 5:00 下午
---
local lw_util = require("Tilua.utils.util")

local user = {}

function user.register(ctx)
    local jgs = ctx.model.jigou:cache(false):select()
    return 'register.html', {
        jgma = jgs
    }
end

function user.create(ctx)
    local req = ctx.request.body
    if not ctx.midware.csrf:check() then
        ctx.response.status = 403
        return
    end
    local user_model = ctx.model.user
    if user_model:where({
        uname = req.uname,
    })           :find() then
        return ctx.response:jump('/user/register', false, '用户名已被注册，请重试!')
    end
    local userdata = {
        uname = req.uname,
        upwd = lw_util.md5(req.upwd),
        name = req.name,
        lwhc_uname = req.lwhc_uname,
        lwhc_upwd = req.lwhc_upwd,
        jgma = req.jgm,
        operNo = req.operNo,
        regIp = ctx.request.remote_addr
    }
    local result = user_model:add(userdata)
    if result.affected_rows == 1 then
        return ctx.response:jump('/user/login', true, '注册成功！')
    else
        return ctx.response:jump('/user/register', false, '注册失败！')
    end
end

function user.login(ctx)
    if ctx.request.method =='GET' then
        return 'login.html',{ip=ctx.request.remote_addr}
    end
    local req = ctx.request.body
    local user_model = ctx.model.user
    local username = req.username
    local password = req.password
    local userinfo = user_model:where({
        uname = username,
        upwd = lw_util.md5(password) }):find()

    if userinfo then
        ctx.session:set("user", userinfo)
        return ctx.response:jump('/', true, '登录成功！')
    else
        return ctx.response:jump('/user/login', true, '登录失败，用户名或者密码不正确！')
    end
end

function user.logout(ctx)
    ctx.session:destroy()
    ctx.response.redirect('/user/login')
end

return user
