---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/2 4:40 下午
---

local M = {}

function M.index(self, ctx)
    local request, _ = ctx:unpack()
    local req = request.body
    local page = req.page or 1
    local limit = req.limit or 10
    return {
        code = 0,
        count = ctx.model[self.table]:count(),
        data = ctx.model[self.table]:limit((page - 1) * limit, limit):select(),
        page = page,
        limit = limit
    }
end

function M.new(self, ctx)
   --todo
end

function M.show(self, ctx, id)
    local services = ctx.model[self.table]
    local data = services:find(id)
    return {
        code = not data and -1 or 0,
        data = data or nil
    }
end

function M.edit(self, ctx, id)
    --todo
end

function M.create(self, ctx)
    local req = ctx.request.body
    local code = 0
    local data, msg
    if self.before_create then
        data, msg = self.before_create(ctx)
    else
        data = req
    end
    if data then
        local services = ctx.model[self.table]
        local result = services:add(data)
        if result.affected_rows == 1 then
            if self.after_create then
                self.after_create(ctx, result.insert_id, data)
            end
        else
            code = -1
        end
    else
        code = -1
    end
    return {
        code = code,
        msg = msg
    }
end

function M.update(self, ctx, id)
    local request, _ = ctx:unpack()
    local req = request.body
    local code = 0
    local data, msg
    if self.before_update then
        data, msg = self.before_update(ctx)
    else
        data = req
    end
    if data then
        local services = ctx.model[self.table]
        local result = services:where({ id = id }):save(data)
        if result.affected_rows == 1 then
            if self.after_update then
                self.after_update(ctx, id, data)
            end
        else
            code = -1
        end
    else
        code = -1
    end
    return {
        code = code,
        msg = msg,
    }
end

function M.destroy(self, ctx, id)
    local code = 0
    local msg = ''
    if self.before_destroy then
        local data
        data, msg = self.before_destroy(ctx, id)
        if data then
            local services = ctx.model[self.table]
            local result = services:where({ id = id }):delete()
            if result.affected_rows == 1 then
                if self.after_destroy then
                    self.after_destroy(ctx, id)
                end
            end
        else
            code = -1
        end
    else
        local services = ctx.model[self.table]
        local result = services:where({ id = id }):delete()
        code = result.affected_rows == 1 and 0 or -1
    end
    return {
        code = code,
        msg = msg,
    }
end
local mt = {
    __index = function(self, name)
        if M[name] then
            return function
            (...)
                return M[name](self, ...)
            end
        end
    end
}

function M.derive(t)
    return setmetatable(t, mt)
end

return M