---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/18 5:10 下午
---

local M = require('Tilua.midware.base').define()

function M.init_worker(ctx)
    ngx.log(ngx.ERR,"M.init_worker" )
end

return M