---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/18 5:10 下午
---

local M = require('Tilua.midware.base').define()
local get_now_ms = require("Tilua.utils.util").get_now_ms
local pl_date = require("pl.Date")
local uuid = require("Tilua.utils.util").random_string
local encode = require("Tilua.utils.util").json_encode
local decode = require("Tilua.utils.util").json_decode

local ngx = ngx

local monitor_shd = ngx.shared.monitor
function M:_construct(ctx, config)
    if not monitor_shd then
        error("midware need ngx.shared shdict ")
    end
    self.access = {

    }
end

---handle_worker
---context ngx.timer
---@param app app
function M:handle_worker()
    local delay = self.config.delay  -- in seconds
    local new_timer = ngx.timer.at
    local log = ngx.log
    local ERR = ngx.ERR
    local check

    check = function(premature)
        if not premature then
            local ok, err = new_timer(delay, check)
            if not ok then
                log(ERR, "failed to create timer: ", err)
                return
            end
        end
        local app_instance = ApiGateWay()
        local access_log = monitor_shd:lpop('access_log')
        while access_log do
            access_log = decode(access_log)
            access_log.id = uuid()
            app_instance.model.access_log:add(access_log)
            access_log = monitor_shd:lpop('access_log')
        end
        app_instance:release()
    end

    local hdl, err = new_timer(delay, check)
    if not hdl then
        log(ERR, "failed to create timer: ", err)
        return
    end
end

---handle
---context M
---@param next function
function M:handle(next, ...)
    local req = self.ctx.request
    self.access.request_time = ngx.req.start_time() * 1000
    self.access.request_time_fmt = pl_date.Format("yyyy-mm-dd HH:MM:SS"):tostring(ngx.req.start_time())
    self.access.request_time_month_span = pl_date.Format("yyyy-mm"):tostring(ngx.req.start_time())
    self.access.request_time_day_span = pl_date.Format("yyyy-mm-dd"):tostring(ngx.req.start_time())
    self.access.request_time_hour_span = pl_date.Format("yyyy-mm-dd_HH"):tostring(ngx.req.start_time())

    self.access.server_port = req.server_port
    self.access.remote_addr = req.remote_addr
    self.access.user_agent = req.header.user_agent
    self.access.host = req.host
    self.access.raw_request = req.raw_request
    self.access.method = req.method
    self.access.path = req.uri
    self.access.server_protocol = req.server_protocol
    self.access.server_name = req.server_name
    self.access.scheme = req.scheme

    self.access.request_platform = req.platform
    self.access.request_browser = req.browser
    self.access.request_mobile = req.mobile or ''
    self.access.request_robot = req.robot or ''
    self.access.request_wechat = req.wechat
    return next(...)
end

---handle_header_filter
---context M
function M:handle_header_filter()
    self.access.response_content_type = ngx.header.content_type
    self.access.response_content_length = ngx.header.content_length
    self.access.response_code = ngx.status
    self.access.response_time = pl_date.Format("yyyy-mm-dd HH:MM:SS"):tostring(ngx.now())
    self.access.request_elapsed_time = ngx.now() * 1000 - self.access.request_time
    if ngx.ctx.peer and ngx.ctx.peer.router then
        self.access.serviceid = ngx.ctx.peer.router.responser.serviceid
        self.access.routeid = ngx.ctx.peer.router.route.id
        self.access.upstream_host = ngx.ctx.peer.host
        self.access.upstream_port = ngx.ctx.peer.port
    else
        self.access.serviceid = 0
        self.access.routeid = 0
        self.access.upstream_host = ''
        self.access.upstream_port = ''
    end
end

function M:handle_log()
    monitor_shd:rpush('access_log', encode(self.access))
end

return M