---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/12 7:41 下午
---
local M = require('Tilua.midware.base').define()
local apiv1 = require("ApiGateWay.util").apiv1
local encode = require("Tilua.utils.util").json_encode
local update = require("pl.tablex").update
local split = require("pl.stringx").split

function M:_construct(ctx, config)
    ctx.logger:debug("ApiGateWay.midware.sign_chek init config:",encode(config))
    self.config = update({
        tokenName = 'accessToken',
        tokenFrom = 'query'
    },config)
end

function M:get_token()
    local request = self.ctx.request
    return request[self.config.tokenFrom][self.config.tokenName]
end

function M:handle(next, ...)
    local accessToken =  self:get_token()
    local fileid,token,sign = table.unpack(split(accessToken or '','.'))
    if not fileid or not token or not sign then
        return 403
    end
    local signS = apiv1({
        service = "token",
        action = "sign",
        data= {
            accessToken= token,
            businessData= fileid
        }
    })

    if signS ~= sign then
        return 403
    end

    return next(...)
end

return M