---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/7/29 5:58 下午
---token_check.lua
---

local token_check = require('Tilua.midware').derive()
local apiv1 = require("ApiGateWay.util").apiv1
local encode = require("Tilua.utils.util").json_encode
local update = require("pl.tablex").update
local ngx_req = ngx.req

function token_check:_init(ctx, config)
    self:super(ctx)
    ctx.logger:debug("ApiGateWay.midware.token_check init config:",encode(config))
    self.config = update({
        tokenName = 'accessToken',
        tokenFrom = 'query'
    },config)
end

function token_check:get_token()
    local request = self.ctx.request
    return request[self.config.tokenFrom][self.config.tokenName]
end

function token_check:handle(next, ...)
    if apiv1({
        service = "token",
        action = "valid",
        data = {
            accessToken = self:get_token()
        } }) then
        return next(...)
    end
    return 403
end

return token_check