---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/7/29 5:58 下午
---token_check.lua
---

local token_check = require('Tilua.midware').derive()
local apiv1 = require("ApiGateWay.util").apiv1
local ngx_req = ngx.req

function token_check:_init(...)
    self:super(...)
end

function token_check:handle(next, ...)
    local request = ngx_req.get_uri_args()
    if apiv1({
        service = "token",
        action = "valid",
        data = {
            accessToken = request.accessToken or self.ctx.request.header.accessToken
        } }) then
        return next(...)
    end
    return 403
end

return token_check