---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/5/30 6:34 下午
---
local lw_util = require('Tilua.utils.util')
local bind1 = require("pl.utils").bind1
local deepcopy = require("pl.tablex").deepcopy
local rawget, type, setmetatable = rawget, type, setmetatable
---@class cache_manager
local manager = {}

function manager:close()
    self.logger:debug('cache instances start to release ')
    lw_util.foreach(self.instances, function(inst)
        inst:close()
    end)
end

function manager:instance(name)
    local config = nil
    local tconfig = type(name)
    if tconfig == 'string' then
        config = deepcopy(self.ctx[name])
    elseif tconfig == 'table' then
        config = deepcopy(name)
    end
    if not config then
        error('cache manager instance failed config is not correct')
    end
    local hash = lw_util.get_hash(config)
    if self.instances[hash] then
        return self.instances[hash]
    end
    self.logger:debug('[Cache Manager] instance cache with config:', lw_util.json_encode(config))
    local driver = lw_util.import(config.driver)
    if not driver then
        error('unsupported cache type ' .. config.driver)
    end
    self.instances[hash] = driver(config, self.ctx, self.logger)
    return self.instances[hash]
end

---get
---@param key string
function manager:get(key)
    if not self.handler then
        self.handler = manager.instance(self, self.ctx.data_cache_handler)
    end
    return self.handler:get(self.handler.config.prefix .. key)
end
---set
---@param name string
---@param value any
---@param expire number
function manager:set(name, value, expire)
    if not self.handler then
        self.handler = manager.instance(self, self.ctx.data_cache_handler)
    end
    return self.handler:set(self.handler.config.prefix .. name, value, expire)
end

---exists
---@param name string
function manager:exists(name)
    if not self.handler then
        self.handler = manager.instance(self, self.ctx.data_cache_handler)
    end
    return self.handler:exists(self.handler.config.prefix .. name) == 1
end
---del
---@param name string
function manager:del(name)
    if not self.handler then
        self.handler = manager.instance(self, self.ctx.data_cache_handler)
    end
    return self.handler:del(self.handler.config.prefix .. name)
end

local function new(self,context, logger)
    return setmetatable({
        ctx = context,
        logger = logger,
        handler = nil,
        instances = {}
    }, {
        __index = function(this, name)
            if name == 'handler' then
                return nil
            end ;
            local rawp = rawget(manager, name)
            local trawp = type(rawp)
            if trawp == 'function' then
                return bind1(rawp, this)
            elseif trawp == 'string' then
                return manager[rawp]
            else
                return manager.instance(this, name)
            end
        end
    })
end

setmetatable(manager,{
    __call = new
})

return manager