---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/6/1 3:17 下午
---
local require = require
local lw_utils = require('Tilua.utils.util')
local bind1 = require("pl.utils").bind1
local deepcopy = require("pl.tablex").deepcopy
local rawget, type, setmetatable, string_lower, string_sub = rawget, type, setmetatable, string.lower, string.sub
---@db_manager
local manager = {}

function manager:instance(config)
    if config == self then
        config = nil
    end
    config = manager.parse_config(self, config)
    assert(config, "db config is not valid")
    local hash = lw_utils.get_hash(config)
    if not self.instances[hash] then
        local driver_type = string_lower(config.type)
        assert(driver_type == 'mysql', 'not support db driver' .. driver_type)
        self.logger:debug("start init db driver named ", driver_type, " with config ", lw_utils.json_encode(config))
        local db_driver = require("Tilua.db.driver." .. driver_type)
        self.instances[hash] = db_driver(config, self.ctx, self.logger)
    end
    return self.instances[hash]
end

function manager:parse_config(config)
    local app_config = self.ctx
    local tconfig = type(config)
    if tconfig == 'string' and config ~= '' then
        local dsn = lw_utils.parse_url(config)
        if dsn then
            return {
                type = dsn.scheme,
                username = dsn.user,
                password = dsn.pass,
                hostname = dsn.host,
                hostport = dsn.port,
                database = string_sub(dsn.path, 2),
                charset = dsn.fragment,
                debug = dsn.params.debug or false
            }
        end
        local _config = app_config[config]
        local _tconfig = type(_config)
        if _config then
            if _tconfig == 'table' then
                return deepcopy(_config)
            elseif _tconfig == 'string' then
                return manager.parse_config(self, _config)
            elseif _tconfig == 'function' then
                _config(self)
            end
            return nil
        end
        return nil
    elseif tconfig == 'table' then
        return config
    elseif tconfig == 'function' then
        return config(self)
    elseif tconfig == 'nil' or (tconfig == 'string' and #config == 0) then
        local db_config = self.ctx
        return {
            type = db_config.db_type,
            username = db_config.db_user,
            password = db_config.db_pwd,
            hostname = db_config.db_host,
            hostport = db_config.db_port,
            database = db_config.db_name,
            charset = db_config.db_charset,
            debug = db_config.db_debug
        }
    end
end
function manager:close()
    self.logger:debug('db connections instance handle close')
    lw_utils.foreach(self.instances, function(db_inst)
        db_inst:close()
    end)
end

local function new(_,ctx)
    return setmetatable({
        ctx = ctx.ctx,
        logger = ctx.logger,
        instances = {}
    }, {
        __index = function(this, name)
            local rawp = rawget(manager, name)
            local trawp = type(rawp)
            if trawp == 'function' then
                return bind1(rawp, this)
            elseif trawp == 'string' then
                return rawp
            else
                return manager.instance(this, name)
            end
        end
    })
end

setmetatable(manager,{
    __call = new
})

return manager