---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/6/1 10:41 上午
---
---
local lw_utils = require('Tilua.utils.util')
local bind1 = require("pl.utils").bind1
local rawget, type, setmetatable = rawget, type, setmetatable
local model_class = require('Tilua.model.model')

local manager = {}

function manager:instance(name, connection)
    self.logger:debug("start Init Model named ", name)
    local mod = lw_utils.import(table.concat({
        self.ctx.name,
        'model',
        name
    }, '.'))
    if mod then
        self.models[name] = mod()
        return self.models[name]
    end
    if self.models[name] then
        self.logger:debug("Model named ", name, " has already inited ")
        return self.models[name]
    end
    self.models[name] = model_class(self.ctx, name, nil, connection or '')
    return self.models[name]
end

local function new(self, ctx)
    return setmetatable({
        ctx = ctx,
        logger = ctx.logger,
        models = {}
    }, {
        __index = function(this, name)
            local rawp = rawget(manager, name)
            local trawp = type(rawp)
            if trawp == 'function' then
                return bind1(rawp, this)
            elseif trawp == 'string' then
                return rawp
            else
                return manager.instance(this, name)
            end
        end
    })
end

setmetatable(manager, {
    __call = new
})

return manager