---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/5/29 4:36 下午
---
local json_encode = require("Tilua.util").json_encode
local json_decode = require("Tilua.util").json_decode

local reverseTable = require("Tilua.util").reverseTable
local bind1 = require("pl.utils").bind1
local proxy_dispatch = require("Tilua.dispatch").derive()
local trim = require("pl.stringx").strip
local dns = require("resty.dns.client")

local reduce = require("pl.tablex").reduce

local balancers = {}

function proxy_dispatch:_init(ctx)
    dns.init()
    self:super(ctx)
end

function proxy_dispatch:add_targets_to_balancer(balancer, targets, start)
    for i = start, #targets do
        local target = targets[i]
        if target.weight > 0 then
            assert(balancer:addHost(target.name, target.port, target.weight))
        else
            assert(balancer:removeHost(target.name, target.port))
        end
    end
end

function proxy_dispatch:create_balancer(upstream, force_create)
    local model = self.ctx.model
    local balancer_types = {
        ["consistent-hashing"] = require("resty.dns.balancer.ring"),
        ["least-connections"] = require("resty.dns.balancer.least_connections"),
        ["round-robin"] = require("resty.dns.balancer.ring")
    }
    local health_threshold = upstream.healthchecks and
            upstream.healthchecks.threshold or nil

    if balancers[upstream.id] and not force_create then
        return balancers[upstream.id]
    end

    local balancer, err = balancer_types[upstream.algorithm].new({
        log_prefix = "upstream:" .. upstream.name,
        wheelSize = upstream.slots, -- will be ignored by least-connections
        dns = dns,
        healthThreshold = health_threshold,
    })
    if not balancer then
        return nil, "failed creating balancer:" .. err
    end

    local targets = model.targets:where({
        upstreamid = upstream.id
    })                   :select()

    self:add_targets_to_balancer(balancer, targets, 1)
    balancers[upstream.id] = balancer

end

function proxy_dispatch:run(router)
    local ctx = self.ctx
    self.ctx.logger:debug("upstream uri ", json_encode(router))
    local model = ctx.model
    if not router.proxy then
        ngx.exit(404)
        return
    end
    if router.proxy.type == 'baffle' then
        self:make_chain_call(router.midware, function()
            local baffle = model.baffle:find(router.proxy.serviceid)
            local response = ctx.response
            local header = json_decode(baffle.header)
            for _, h in ipairs(header) do
                for k, v in pairs(h) do
                    response.headers[k] = v
                end
            end
            return baffle.body
        end)()
        ctx.response:send()
        return ;
    else
        local service = model.services:cache(not self.ctx.debug):find(router.proxy.serviceid)
        local matched_route = router.router.route
        local upstream_base
        if not service then
            ngx.exit(404)
            return
        end

        if service.path == ngx.null then
            upstream_base = '/'
        else
            upstream_base = '/' .. trim(service.path, '/')
        end
        local targets
        local upstream = model.upstreams:cache(not self.ctx.debug):where({
            name = service.host
        })                    :find()
        self.ctx.logger:debug("upstream  ", json_encode(upstream))

        if upstream then
            targets = model.targets:cache(not self.ctx.debug):where({
                upstreamid = upstream.id
            })             :select()
        end

        ngx.var.upstream_scheme = service.protocol
        if matched_route.strip_path == 1 then
            local striped_path = table.concat(router.params, '/')

            if matched_route.path_handle == 'v1' then
                ngx.var.upstream_uri = upstream_base .. striped_path
            else
                ngx.var.upstream_uri = upstream_base .. "/" .. striped_path
            end
        else
            local striped_path = trim(ctx.request.path_info, '/')

            if matched_route.path_handle == 'v1' then
                ngx.var.upstream_uri = upstream_base .. striped_path
            else
                ngx.var.upstream_uri = upstream_base .. "/" .. striped_path
            end
        end

        self.ctx.logger:debug("upstream uri ", ngx.var.upstream_uri)

        ngx.var.upstream_connection = ctx.request.header.connection or ''
        if matched_route.preserve_host == 1 then
            ngx.var.upstream_host = ctx.request.http_host or ctx.request.host .. ":" .. ctx.request.server_port
        elseif upstream then
            ngx.var.upstream_host = upstream.host_header ~= "" and upstream.host_header or "TiluaApiGateway"
        else
            ngx.var.upstream_host = "TiluaApiGateway"
        end
        local ip, port, host, hanlde
        if upstream then
            local balancer = self:create_balancer(upstream)
            ip, port, host, hanlde = balancer:getPeer(true)
        else
            ip = service.host
            port = service.port
        end

        self.ctx.logger:debug("upstream uri ", ip, port)

        ngx.ctx.peer = {
            host = ip,
            port = port,
            connect_timeout = service.connect_timeout,
            send_timeout = service.write_timeout,
            read_timeout = service.read_timeout
        }
    end

end

return proxy_dispatch