---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/5/29 4:36 下午
---

local proxy_dispatch = require("Tilua.dispatch").derive()
function proxy_dispatch:_init(ctx)
    self:super(ctx)
end
function proxy_dispatch:run()
    self.ctx.logger:debug("proxy_dispatch:run")
    local balancer = require("ngx.balancer")
    local host = "32.254.48.88"
    local port = 80

    local ok, err = balancer.set_current_peer(host, port)
    balancer.set_timeouts(60,60,60)
    if not ok then
        ngx.log(ngx.ERR, "failed to set the current peer: ", err)
        return ngx.exit(500)
    end
end
return proxy_dispatch