---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/4 10:14 上午
---
local lw_util = require("Tilua.utils.util")
local derive = require "Test.controller.base.rest".derive
local we = require "resty.worker.events"

local M = {
    table = 'certificate',
    view = 'certificate'
}
function M.before_create(ctx)
    local request, _ = ctx:unpack()
    local req = request.body
    return {
        server_name = req.server_name,
        cert = req.cert,
        cert_key = req.cert_key,
        created_at = { 'exp', 'now()' },
        updated_at = { 'exp', 'now()' },
        status = 1
    }
end

function M.after_create(ctx, insert_id, data)
    data.id = insert_id
    we.post('certificate', 'add', data)
end

function M.before_update(ctx, id)
    local request, _ = ctx:unpack()
    local req = request.body

    return {
        server_name = req.server_name,
        cert = req.cert,
        cert_key = req.cert_key,
        created_at = { 'exp', 'now()' },
        updated_at = { 'exp', 'now()' },
        status = req.status
    }
end

function M.after_update(ctx, id, data)
    data.id = id
    we.post('certificate', 'update', data)
end

function M.after_destroy(ctx, id)
    we.post('certificate', 'delete', id)
end


return derive(M)