---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/3 2:38 下午
---
local we = require "resty.worker.events"

local util = require("Tilua.util")
local M = {}

function M.add(ctx,objecttype,id)
    local method = ctx.request.method
    if method =='GET' then
        local plugins = ctx.model.midwares:where({ status = 1 }):select()
        return "plugins/add.html",{
            objecttype = objecttype,
            id = id,
            plugins = plugins
        }
    else
        local request, response = ctx:unpack()
        local req = request.body
        local configs = type(req.config) == 'table' and table.concat(req.config, ',') or req.config

        local services = ctx.model.plugins
        if services:where({
            objecttype = objecttype,
            mid = req.mid,
            objectid = id

        }):find() then
            return {
                code = -1,
                msg = "请勿重复添加插件",
            }
        end
        local result = services:add({
            objectid = id,
            objecttype = objecttype,
            phase = req.phase,
            mid = req.mid,
            status = 1,
            indexNo = 10,
            config = configs,
            created_at = { 'exp', 'now()' },
            updated_at = { 'exp', 'now()' }
        })
        --if result.affected_rows == 1 then
        --    we.post('route', 'add_plugin', req.routeid, true)
        --end
        response.body = {
            code = result.affected_rows == 1 and 0 or -1,
            msg = "错误",
        }
    end
end

function M.destroy(ctx,id)
    local services = ctx.model.plugins
    local result = services:where({ id = id }):delete()
    return {
        code = result.affected_rows == 1 and 0 or -1,
        msg = "",
    }
end

function M.order(ctx,id,index)
    local services = ctx.model.plugins
    local result = services:where({ id = id }):save({
        indexNo = index
    })
    return {
        code = result.affected_rows == 1 and 0 or -1,
        msg = "",
    }
end
function M.index(ctx,objecttype,id)
    local req = ctx.request.body
    local db = ctx.db.instance()
    local sql = [[select plugins.*,mid.name,mid.package from plugins left join midwares as mid
    on (mid.id=plugins.mid) where  plugins.objectid = ]]
    local data = db:query(sql .. id .." and plugins.objecttype=\""..objecttype.."\" order by  plugins.indexNo asc,plugins.phase asc,plugins.id asc" )
    return {
        code = 0 ,
        data = data
    }
end

function M.edit(ctx,id)
    local method = ctx.request.method
    local req = ctx.request.body
    if method =='GET' then
        local services = ctx.model.plugins
        local result = services:where({ id = id }):find()
        result.config = util.split(result.config == ngx.null and "" or result.config, ',')
        return 'plugins/edit.html',result
    else
        local services = ctx.model.plugins
        local configs = type(req.config) == 'table' and table.concat(req.config, ',') or req.config
        local result = services:where({ id = id }):save({
            config = configs,
            updated_at = { 'exp', 'now()' }
        })
        return {
            code = result.affected_rows == 1 and 0 or -1,
            msg = "",
        }
    end
end

function M.manage(ctx)
    local request, _ = ctx:unpack()
    local req = request.body
    return 'plugins/manage.html',req
end

return M