---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/8/5 11:15 下午
---

local M = require("Tilua.utils.class").define()

function M:_construct(ctx, config)
    self.ctx = ctx
    self.config = config
end

---handle
function M:handle(...)
    error("Midware class method handle must override!")
end

return M