---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/4/20 3:10 下午
--- body_parser.lua
---
local ngx = ngx
local var = ngx.var

local class = require('pl.class')
local req = ngx.req
local read_body = req.read_body
local util = require("Tilua.util")
local pl_utils = require("pl.utils")
local strip = require("pl.stringx").strip
local split = require("pl.stringx").split
local string_startsWith = require("pl.stringx").startswith
local tablex = require("pl.tablex")

local map = tablex.map
local path = require "pl.path"
local dirname = path.dirname
local getmtime = path.getmtime
local io_open = io.open
local makepath = require "pl.dir".makepath
local path_exists = path.exists

---@class body_parser
local body_parser = require('Tilua.midware').derive()
local _config = nil
local _sock = nil
---parse_disposition_headers
---@param headers table
local function parse_disposition_headers(headers)
    local name, filename, type, error, encoding
    map(function(v)
        if string_startsWith(v, "Content-Disposition") then
            -- file
            local ct, field, file_fields = pl_utils.unpack(split(v, ";"))
            ct = split(ct, ":")
            if ct[2] == " form-data" then
                if field then
                    field = split(field, "=")
                    name = strip(field[2], "\"")
                end
                if file_fields then
                    file_fields = split(file_fields, "=")
                    filename = strip(file_fields[2], "\"")
                end
            end
        elseif string_startsWith(v, "Content-Type") then
            local ct, charset = pl_utils.unpack(split(v, ";"))
            ct = split(ct, ":")
            type = strip(ct[2])
            if charset and string_startsWith(charset, 'charset') then
                charset = split(charset, "=")
                encoding = charset[2]
            else
                encoding = "utf8"
            end
        elseif string_startsWith(v, "Content-Transfer-Encoding") then
        end
    end, headers)
    return {
        name = name,
        origin_filename = filename,
        type = type or "text/plain",
        error = error,
        charset = encoding
    }
end
local function get_boundary(content_type)
    local boundary = string.match(content_type or "", ";%s*boundary=([^,;]+)")
    boundary = strip(boundary or "", '"')
    return boundary
end
local function is_multipart(content_type)
    return string_startsWith(content_type, 'multipart/form-data')
end
local function is_json(content_type)
    if string_startsWith(content_type, 'application/json') or
            string_startsWith(content_type, 'application/vnd.api+json') or
            string_startsWith(content_type, 'application/csp-report') then
        return true
    end
    return false
end
local function is_form(content_type)
    return string_startsWith(content_type, 'application/x-www-form-urlencoded')

end
local function get_limit_size(typ)
    local limit_size = _config[typ]
    if util.is_number(limit_size) then
        return limit_size
    elseif util.is_string(limit_size) then
        limit_size = string.lower(limit_size)
        limit_size = string.gsub(limit_size, 'mb', '000000')
        limit_size = string.gsub(limit_size, 'kb', '000')
        return tonumber(limit_size)
    end
end

local function parse_form()
    read_body()
    return req.get_post_args()
end

local function parse_json()
    read_body()
    local data = req.get_body_data()
    if data then
        return util.json_decode(data)
    end
    return {}
end
local function read_post_file(part, read)
    local chunk_size = _config.chunk_size
    local upload_tmp_dir = _config.tmpdir
    local uuid = util.uuid()
    local body, err = read(chunk_size)
    local discard_body_part = function
    ()
        while true do
            body, _ = read(chunk_size)
            if not body then
                break
            end
        end
    end
    if not body then
        discard_body_part()
    else
        if part.origin_filename and part.origin_filename ~= "" then
            local ext = path.extension(part.origin_filename or "")
            if not tablex.find(_config.whitelist, ext) and not tablex.find(_config.file_extensions, ext) then
                part.error = "Invalid filename: " .. part.origin_filename
                discard_body_part()
            else
                local upload_file_tmp = io_open(upload_tmp_dir .. uuid, 'a+')
                upload_file_tmp:write(body)
                while true do
                    body, _ = read(chunk_size)
                    if not body then
                        upload_file_tmp:close()
                        part.filename = upload_tmp_dir .. uuid
                        break
                    else
                        upload_file_tmp:write(body)
                        part.size = upload_file_tmp:seek("end")
                        if part.origin_filename and part.size > get_limit_size('file_size') then
                            part.error = "Request file too large, please check multipart config"
                            upload_file_tmp:close()
                            discard_body_part()
                            break
                        end
                    end
                end
            end
        elseif not part.origin_filename then
            local body_temp = body
            while true do
                body, _ = read(chunk_size)
                if not body then
                    break
                else
                    body_temp = body_temp .. body
                end
            end
            part.value = body_temp
        end
    end
    return part
end
local function parse_multipart(boundary)
    if boundary then
        local err
        _sock, err = req.socket()
        if not _sock then
            assert(_sock, "ngx.req.socket init failed " .. err)
        end
        local read_line, err = _sock:receiveuntil("\r\n")
        local read_post_body, _ = _sock:receiveuntil("\r\n--" .. boundary)
        if not read_line then
            return {}
        end
        if not path_exists(_config.tmpdir) then
            makepath(_config.tmpdir)
        end

        local multiparts = {}
        local preamble, err = read_line()
        if not preamble then
            return {}
        end
        local header = ""
        local data
        while true do
            local disposition_headers = {}
            while true do
                header, _ = read_line()
                if header == "" then
                    break
                else
                    disposition_headers[#disposition_headers + 1] = header
                end
            end
            local part = parse_disposition_headers(disposition_headers)
            multiparts[#multiparts + 1] = read_post_file(part, read_post_body)
            data, _ = read_line()
            if data == '--' then
                break
            end
        end
        return multiparts
    end
end

local function parse_args(data)
    return util.json_decode(data) or ngx.decode_args(data) or {}
end

function body_parser:handle(next, ...)
    ---@type app
    local ctx = self.ctx
    local request, response = ctx:unpack()
    local request_content_type = request.header.content_type
    request.body = req.get_uri_args()
    if request_content_type then
        if is_form(request_content_type) then
            request.body = parse_form()
        elseif is_multipart(request_content_type) then
            local boundary = get_boundary(request_content_type)
            request.body.files = parse_multipart(boundary)
        elseif is_json(request_content_type) then
            request.body = parse_json()
        else
            read_body()
            request.body = parse_args(req.get_body_data())
        end
    else
        read_body()
        local body_file = req.get_body_file()
        if body_file then
            local content = pl_utils.readfile(body_file)
            if content then
                request.body = parse_args(content)
            end
        end
    end
    return next(...)
end

function body_parser:_init(ctx)
    self:super(ctx)
    _config = ctx.config.multipart
end
return body_parser