---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyang.
--- DateTime: 2020/6/26 11:05 上午
---csrf_token.lua
---
local csrf_token = require('Tilua.midware').derive()
local lw_util = require("Tilua.util")
csrf_token.alias = 'csrf'

function csrf_token:_init(...)
    self:super(...)
end

function csrf_token:token()
    local token = lw_util.uuid()
    self.ctx.session:set('csrf_token', token)
    return '<input type="hidden" name="csrftoken" value="' .. token .. '"/>'
end

function csrf_token:handle(next, ...)
    self.ctx.view:mount_context('__CSRF__', function()
          return self:token()
    end)
    return next(...)
end

function csrf_token:check()
    local request, _ = self.ctx:unpack()
    local req = request.body
    local csrftoken = req.csrftoken or request.header.csrftoken or nil
    if not csrftoken or csrftoken ~= self.ctx.session:get('csrf_token') then
        self.ctx.session:unset('csrf_token')
        return false
    end
    self.ctx.session:unset('csrf_token')
    return true
end

return csrf_token